SELECT * FROM dim_customers;
SELECT * FROM dim_products;
SELECT * FROM fact_sales;

-- Explore all the Objects in the Database 
SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- Explore all the columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

-- Dimension Explorations
SELECT DISTINCT country
FROM dim_customers;

SELECT DISTINCT product_name
FROM dim_products

SELECT DISTINCT product_line
FROM dim_products

SELECT DISTINCT category
FROM dim_products

SELECT DISTINCT subcategory
FROM dim_products

	-- Date Explorations
	-- First and Last Order Date and Range 
	SELECT 
		MIN(order_date) AS First_ord,
		MAX(order_date) AS Last_ord,
		DATEDIFF(YEAR ,MIN(order_date),MAX(order_date)) AS Order_Range,
		DATEDIFF(MONTH ,MIN(order_date),MAX(order_date)) AS Order_Range_Month
	FROM fact_sales

	--  Youngest and Oldest Customers
	SELECT 
		MIN(birthdate) AS Old,
		MAX(birthdate) AS Young,
		DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS Old_Age,
		DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS Young_Age
	FROM dim_customers

	-- Key Metrics
	--Find the Total Sales
	SELECT	
		CAST(ROUND(SUM(sales_amount)/1000000,2) AS varchar(10)) + 'Millions'  AS Total_Sales
	FROM fact_sales

	--Find the Average Selling Price
	SELECT 
		ROUND(AVG(price),2) AS Avg_Price
	FROM fact_sales

	-- Find the Total Items Sold
	SELECT 
		SUM(quantity) AS Total_Quantity
	FROM fact_sales
 
	 --Find the Total No of Orders
	 SELECT 
		COUNT(DISTINCT order_number) AS Total_Orders
	 FROM fact_sales

	 -- Magnitude Analysis :  
	 -- Total_Sales By Categories
	 SELECT 
		P.category,
		SUM(F.sales_amount) AS Total_Sales
	 FROM fact_sales AS F
	 LEFT JOIN dim_products AS P
	 ON F.product_key = P.product_key
	 GROUP BY P.category
	 ORDER BY Total_Sales DESC

	 --TOP 10- Total_Sales By Products
	  SELECT 
		TOP 10
		P.product_name,
		SUM(F.sales_amount) AS Total_Sales
	 FROM fact_sales AS F
	 LEFT JOIN dim_products AS P
	 ON F.product_key = P.product_key
	 GROUP BY P.product_name
	 ORDER BY Total_Sales DESC

	 -- Total number of Customer By Country
	 SELECT 
		country,
		COUNT(customer_id) AS Total_Customers
	 FROM dim_customers
	GROUP BY country
	ORDER BY Total_Customers DESC

	-- Total Distribution of items Sold acress Countries
	 SELECT 
		C.country,
		SUM(F.quantity) AS Total_qty
	 FROM fact_sales AS F
	 LEFT JOIN dim_customers C
	 ON F.customer_key = C.customer_key
	 GROUP BY C.country
	 ORDER BY Total_qty DESC

	-- Total Customers by Gender
	SELECT 
		gender AS Gender,
		COUNT(customer_id) AS Total_Customers
	FROM dim_customers
	GROUP BY gender
	ORDER BY Total_Customers DESC

	-- Find the Total Product by Category
	SELECT 
		category,
		COUNT(product_id) AS Total_Products
	FROM dim_products
	GROUP BY category
	ORDER BY Total_Products DESC

	-- Total Revenue generated by Each Customers TOP 10 
	SELECT 
		TOP 10
		C.customer_id,
		C.first_name,
		C.last_name,
		--C.gender,
		SUM(F.sales_amount) AS Total_Revenue
	FROM fact_sales AS F
	LEFT JOIN dim_customers AS C
	ON F.customer_key = C.customer_key
	GROUP BY
		C.customer_id,
		C.first_name,
		C.last_name
		--C.gender
	 ORDER BY Total_Revenue DESC

	 -- Ranking Analysis :
	 -- Top 5 Product generate the highest Revenue
	/*
	 SELECT 
		TOP 5
		P.product_name,
		SUM(F.sales_amount) AS Total_Sales
	 FROM fact_sales AS F
	 LEFT JOIN dim_products P
	 ON F.product_key = P.product_key
	 GROUP BY P.product_name
	 ORDER BY Total_Sales DESC
								---------------------------*/
	 WITH CTE AS (
	 SELECT 
		P.product_name,
		SUM(F.sales_amount) AS Total_Sales,
		ROW_NUMBER() OVER (ORDER BY SUM(F.sales_amount) DESC) AS Rnk
	 FROM fact_sales F
	 LEFT JOIN dim_products AS P
	 ON F.product_key = P.product_key
	 GROUP BY 
	 P.product_name
	 ) 
	 SELECT 
		product_name,
		Total_Sales
	 FROM CTE
	 WHERE Rnk <=5

	--  Top 5 Product generate the lowest Revenue
	  SELECT 
		TOP 5
		P.product_name,
		SUM(F.sales_amount) AS Total_Sales
	 FROM fact_sales AS F
	 LEFT JOIN dim_products P
	 ON F.product_key = P.product_key
	 GROUP BY P.product_name
	 ORDER BY Total_Sales 

	-- Advanced Analysis :

	-- Change Over Time 

	-- Sales Performance Over Time By Year
	SELECT 
		YEAR(order_date) AS Order_Year,
		SUM(sales_amount) AS Total_Sales
	FROM fact_sales
	WHERE order_date IS NOT NULL
	GROUP BY 
		YEAR(order_date)
	ORDER BY YEAR(order_date)

	-- Sales Performance Over Time By Months AND Customer added Each Months
	SELECT 
		DATETRUNC(MONTH,order_date) AS Order_Month,
		SUM(sales_amount) AS Total_Sales,
		COUNT(DISTINCT customer_key) AS Total_Customers
	FROM fact_sales
	WHERE order_date IS NOT NULL
	GROUP BY 
		DATETRUNC(MONTH,order_date)
	ORDER BY DATETRUNC(MONTH,order_date),Total_Sales DESC

	-- Cumulative Analysis :
	-- Calculate Total Sales by Months and Running Total Over Time

	WITH CTE_Running_Sales1 AS(
	SELECT 
		DATETRUNC(MONTH,order_date) AS Order_Month,
		SUM(sales_amount) AS Total_Sales
	FROM fact_sales
	WHERE order_date IS NOT NULL
	GROUP BY 
		DATETRUNC(MONTH,order_date)
	)
	SELECT 
		Order_Month,
		Total_Sales,
		SUM(Total_Sales) OVER( ORDER BY Order_Month ) AS Running_Total
	FROM CTE_Running_Sales1

	-- Performance Analysis :

	-- Analyze the yearly Performance Products by comparing each products sales to both Average Sales and Previous Year Sales
	;WITH CTE AS(
	SELECT 
		DATETRUNC(YEAR,F.order_date) AS Current_Year,
		P.product_name,
		SUM(F.sales_amount) AS Current_Sales
	FROM fact_sales F
	LEFT JOIN dim_products P
	ON F.product_key = P.product_key
	WHERE order_date IS NOT NULL
	GROUP BY 
		DATETRUNC(YEAR,F.order_date),
		P.product_name
	)
	SELECT 
		Current_Year,
		product_name,
		Current_Sales,
		AVG(Current_Sales) OVER(PARTITION BY product_name ) AS Avg_Sales,
		Current_Sales - AVG(Current_Sales) OVER(PARTITION BY product_name ) AS Difference_Avg,
		LAG(Current_Sales) OVER( PARTITION BY product_name ORDER BY Current_Year) AS Previous_Sales,
		Current_Sales - LAG(Current_Sales) OVER( PARTITION BY product_name ORDER BY Current_Year) AS Difference_Prev_Sales,
		CASE 
			WHEN Current_Sales - LAG(Current_Sales) OVER( PARTITION BY product_name ORDER BY Current_Year) > 0 THEN 'Increase'
			WHEN Current_Sales - LAG(Current_Sales) OVER( PARTITION BY product_name ORDER BY Current_Year) < 0 THEN 'Decrease'
			ELSE 'No-Change'
		END AS Previus_Change
	FROM CTE

	-- Part to Whole Analysis
	-- Which category Contribute the most Overall Sales

	;WITH CTE_Contributions AS (
	SELECT 
		P.category,
		SUM(F.sales_amount) AS Total_Sales
	FROM fact_sales F
	LEFT JOIN dim_products P
	ON F.product_key = P.product_key
	GROUP BY P.category
	)
	SELECT 
		category,
		Total_Sales,
		SUM(Total_Sales) OVER() AS Overall_Sales,
		ROUND((Total_Sales / SUM(Total_Sales) OVER()) * 100,2) AS Contributions
	FROM CTE_Contributions
	ORDER BY Contributions DESC

	-- Customers Segmentations :
	-- Segment Products into Cost range and Count how many Products falls into each segments

	WITH CTE_Segments AS(
	SELECT 
		product_id,
		product_name,
		cost,
		CASE 
			WHEN cost < 100 THEN 'Below 100'
			WHEN cost BETWEEN 100 AND 500 THEN '100-500'
			WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
			WHEN cost BETWEEN 1000 AND 1500 THEN '1000-1500'
			ELSE '1500+'
		END AS Cost_segment
	FROM dim_products
	)
	SELECT 
		Cost_segment,
		COUNT(product_id) AS Total_Products
	FROM CTE_Segments
	GROUP BY Cost_segment
	ORDER BY Total_Products

	/* Group the Customer into Three Segments based on their Spending behavior 
		VIP : Atleast 12 months of history and spend more than 5000
		Regular :  Atleast 12 months of history and spend less than 5000
		New : less than 12 months
		Find the total no of Customer by each Group
	*/

	WITH CTE_life_span AS(
	SELECT 
		C.customer_id,
		SUM(F.sales_amount) AS Total_Sales,
		MIN(F.order_date) AS First_Order,
		MAX(F.order_date) AS Last_Order,
		DATEDIFF(MONTH,MIN(F.order_date),MAX(F.order_date)) AS Life_Span
	FROM fact_sales F
	LEFT JOIN dim_customers C
	ON F.customer_key = C.customer_key
	GROUP BY C.customer_id
	)
	,CTE_Customers AS(
	SELECT 
		customer_id,
		CASE
			WHEN Life_Span >= 12 AND Total_Sales >5000 THEN 'VIP'
			WHEN Life_Span >= 12 AND Total_Sales <= 5000 THEN 'Regular'
			ELSE  'New'
		END AS Customer_Segment
	FROM CTE_life_span
	)
	SELECT 
		Customer_Segment,
		COUNT(DISTINCT customer_id) AS Total_Customers
	FROM CTE_Customers
	GROUP BY Customer_Segment;

	-- Report Genration : Customer Report

	/* Retrive all required Columns from Tables :
		Segment the Categories 
		Aggregation Customer level metrics : TotalSales, TotalOrders, TotalQty
		Valuable KPI's : Recency, AvgOrderValue, AvgMonthSpend
	*/
	GO
	CREATE VIEW Customer_Report 
	AS
	WITH CTE_Customer_Report AS(
	SELECT 
		F.customer_key,
		F.order_number,
		F.order_date,
		F.product_key,
		C.customer_number,
		CONCAT(C.first_name,' ',C.last_name) AS Customer_name,
		DATEDIFF(YEAR,C.birthdate,GETDATE()) AS Age,
		F.sales_amount,
		F.quantity
	FROM fact_sales F
	LEFT JOIN dim_customers C
	ON F.customer_key = C.customer_key
	WHERE F.order_date IS NOT NULL
	)
	,CTE_Customer_Agg AS(
	SELECT 
		MAX(order_date) AS Last_order,
		Customer_name,
		Age,
		customer_key,
		COUNT(DISTINCT order_number) AS Total_Orders,
		SUM(sales_amount) AS Total_Sales,
		SUM(quantity) AS Total_Quantity,
		COUNT(DISTINCT product_key) AS Total_Products,
		DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) AS Life_Span
	FROM CTE_Customer_Report
	GROUP BY
		Customer_name,
		Age,
		customer_key
	)
	SELECT 
		customer_key,
		Customer_name,
		Age,
		Last_order,
		Total_Orders,
		Total_Sales,
		Total_Quantity,
		Total_Products,
		Life_Span,
		CASE 
			WHEN Life_Span >=12 AND Total_Sales >5000 THEN 'VIP'
			WHEN Life_Span >=12 AND Total_Sales <=5000 THEN 'Regular'
			ELSE 'New'
		END AS Customer_Segment,
		DATEDIFF(MONTH,Last_order,GETDATE()) AS Recency,
		Total_Sales / Total_Orders AS AOV,
		CASE 
			WHEN Life_Span = 0 THEN Total_Sales
			ELSE Total_Sales / Life_Span 
		END AS Avg_Monthly_Spend
	FROM CTE_Customer_Agg

	-- Product Report :
	/*
		Gather essential fields such as Product name, Category, SubCategory and Cost.
		Segment Product by Revenue to Identify Performers High, Mid, Low.
		Aggregate Product Metrics
			Total Orders 
			Total Sales
			Total Quantity
			Total Customers
			LifeSpan
		KPI's 
			Recency 
			Average Order Value
			Average Monthly Spend
	*/
	GO
	CREATE VIEW Product_Report 
	AS
	WITH Base_Query AS (
	SELECT 
		F.order_date,
		P.product_key,
		P.product_name,
		P.category,
		P.subcategory,
		P.cost,
		F.sales_amount,
		F.order_number,  
		F.customer_key  
	FROM fact_sales F
	LEFT JOIN dim_products P
	ON F.product_key = P.product_key 
	WHERE order_date IS NOT NULL
	)
	, Product_info AS (
	SELECT 
		product_key,
		product_name,
		category,
		subcategory,
		cost,
		COUNT(DISTINCT order_number) AS Total_Orders,
		SUM(sales_amount) AS Total_Sales,
		COUNT(DISTINCT customer_key) AS Total_Customer,
		DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) AS Life_Span,
		MAX(order_date) AS Last_Order
	FROM Base_Query
	GROUP BY 
		product_key,
		product_name,
		category,
		subcategory,
		cost
	)
	SELECT 
		product_key,
		product_name,
		Total_Customer,
		category,
		subcategory,
		cost,
		Last_Order,
		Life_Span,
		CASE 
			WHEN Total_Sales > 50000 THEN 'High'
			WHEN Total_Sales >=10000 THEN 'Medium'
			ELSE 'Low'
		END AS Performers,
		DATEDIFF(MONTH,Last_Order,GETDATE()) AS Recency_Month,
		Total_Sales / Total_Orders AS Avg_Order_Revenue,
		ROUND(Total_Sales / Life_Span,2) AS Avg_Monthly_Rev,
		Total_Orders,
		Total_Sales
	FROM Product_info;





















